export const BikeEmpty = () => ({
  id: -1,
  name: '',
  description: '',
  productionStart: null,
  productionEnd: null,
  bikeType: null,
  bike_brand: null,
  bike_property: {id: -1},
  maxGears: null,
  slug: '',
  link: '',
  images: [],
  creator: '',
  electric: false,
  smart: false,
});

export const BikeFromRequest = (body) => ({
  id: body.id,
  name: body.name,
  description: body.description,
  productionStart: body.productionStart,
  productionEnd: body.productionEnd,
  bikeType: body.bikeType,
  bike_brand: body.brand,
  maxGears: body.maxGear,
  slug: body.slug,
  images: body.images,
  link: body.link,
  creator: body.creator,
  electric: body.electric,
  smart: body.smart,
});
