export const bikeTypes = [
  'E_CITY_BIKE',
  'E_CARGO_BIKE',
  'E_MOUNTAIN_BIKE',
  'CITY_BIKE',
  'BMX',
  'MOUNTAIN_BIKE',
  'STREET_BIKE',
  'CARGO_BIKE',
];

export const bikeSpecs = {
  range: 'number',
  brakes: 'string',
  motor: 'string',
  battery: 'string',
  tires: 'string',
  production: 'string',
  weight: 'float',
  bikeLength: 'float',
  bikeWidth: 'float',
  price: 'number',
  gear: 'string',
  chain: 'string',
  rear_brake: 'string',
  front_break: 'string',
  rims: 'string',
  rear_deraillieor: 'string',
  front_feraillieur: 'string',
  crank: 'string',
  casette: 'string',
  brake_disc: 'string',
  stem: 'string',
  handlebar: 'string',
  saddle: 'string',
  seatpost: 'string',
  pedals: 'string',
  fork: 'string',
  frame: 'string',
  bottom_bracket: 'string',
}