export const SpecsEmpty = () => ({});

export const  SpecsFromRequest = (body) => ({
  range: body.range,
  brakes: body.brakes,
  motor: body.motor,
  battery: body.battery,
  tires: body.tires,
  production: body.production,
  weight: body.weight,
  bikeLength: body.bikeLength,
  bikeWidth: body.bikeWidth,
  price: body.price,
  gear: body.gear,
  chain: body.chain,
  rear_brake: body.rear_brake,
  front_break: body.front_break,
  rims: body.rims,
  rear_deraillieor: body.rear_deraillieor,
  front_feraillieur: body.front_feraillieur,
  crank: body.crank,
  casette: body.casette,
  brake_disc: body.brake_disc,
  stem: body.stem,
  handlebar: body.handlebar,
  saddle: body.saddle,
  seatpost: body.seatpost,
  pedals: body.pedals,
  fork: body.fork,
  frame: body.frame,
  bottom_bracket: body.bottom_bracket,
});
